version: "3.9"
services:
  backend:
    build: .
    links:
      - influxdb
    depends_on:
      - influxdb
  influxdb:
    env_file:
      - influxdb.env
    image: influxdb:2.6
    ports:
      - 8086:8086
    volumes:
      - type: bind
        source: ./influxdb
        target: /var/lib/influxdb2
  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - type: bind
        source: ./grafana
        target: /var/lib/grafana
    ports:
      - 3000:3000
    links:
      - influxdb
    depends_on:
      - influxdb
